services:
  app:
    build: .
    image: mastaba-v4-image
    container_name: mastaba-v4-container
    restart: always
    ports:
      - "3001:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
